version: '3'

services:

  postgres:
    image: postgres:alpine
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USERNAME : postgres
      POSTGRES_PASSWORD : qweasd123
      POSTGRES_DATABASE : efisherydb
