version: '3'

services:
  postgres:
    image: postgres:alpine
    restart: always
    ports: 
      - "5432:5432"
    environment: 
      POSTGRES_USERNAME : postgres
      POSTGRES_PASSWORD : qweasd123
      POSTGRES_DB : efisherydb

  redis:
    image: redis:latest
    ports:
        - 6379:6379
    volumes:
        - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]